dist: trusty
sudo: false
language: node_js
git:
  depth: 5

#

node_js: 10
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"
install: yarn --frozen-lockfile

jobs:
  include:
    - stage: Test
      name: Lint
      script: yarn lint
    - name: Unit test
      script: yarn test --coverage
      after_success: npx codecov
    - name: Flow
      script: yarn flow
    - name: Build
      script: yarn build
    - name: End to end
      # TODO(douglasduteil): skip the actual test until we have a monorepo
      # > The e2e tests expect to have the api on ../
      # script: yarn cypress:ci
      script: skip
